[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/test"
  to = "/test/"
  status = 301

[[redirects]]
  from = "/test/*"
  to = "/test/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
